# Maven
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: serverlesSecurity@1
  inputs:
    customFlags: '-U jonathan.campbell+saemea@aquasec.com -P "$(PASSWD)" -H https://225fccbcb7.cloud.aquasec.com/'
    showNegligible: false
    connection: 'serverless-nexus'