# Maven

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: aquasecScanner@4
  inputs:
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: 'Artifacts'
    runOptions: 'scan --code-scan . --token "${TOKEN}" --htmlfile AquaSecurity.html --jsonfile AquaSecurity.json'
    connection: 'Serverless-saas'
    caCertificates: true
